# Generated by Django 4.0 on 2021-12-12 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_no',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
